
#Utils
# Expanding function
# Input the space you want expand, the vector space V where it lives and the subfield Fqk to use to expand
# exp (s in the paper) decides how many expansion perform, verbose print the dimensions.
def expand_subspace(R, V, Fqk, exp=3, verbose=False): 
    R_basis = [Fqn(x.list()) for x in R.basis()]
    R_exp = V.subspace(R_basis) 
    for i in range(exp-1):
        if verbose:
            print(f"Iteration {i+1}: dimension so far = {R_exp.dimension()}")
        z = Fqk.random_element() # Choose a random element in Fqk \ Fq
        while z in Fqk.prime_subfield(): #I should also avoid to use z in the space generated by 1 and previous z, as this is rare I just ignore it.
            z = Fqk.random_element()
        R_z_basis = [z * x for x in R_basis] # Multiply each vector in the original R_basis by z
        R_z = V.subspace(R_z_basis)      
        R_exp = R_exp + R_z  # Add the new subspace to the expanded one   
    if verbose:
        print(f"Dimension after expansion = {R_exp.dimension()}")
    return R_exp

# Contracting function
# Input the space you want contract, the vector space V where it lives and the subfield Fqk to use to contract
# intersect decides how many contractions perform, verbose print the dimensions. 
def contract_subspace(R, V, Fqk, intersect=1, verbose=False):
    R_basis = [Fqn(x.list()) for x in R.basis()]
    R_exp = V.subspace(R_basis) # The space we will contract
    R_exp_basis = [Fqn(x.list()) for x in R_exp.basis()] # Basis of the space we contract
    for i in range(intersect):
        if verbose:
            print(f"Iteration {i+1}: dimension so far = {R_exp.dimension()}")
        z = Fqk.random_element() # Choose a random element in Fqk \ Fq
        while z in Fqk.prime_subfield(): # Avoid trivial intersection.
            z = Fqn.random_element()
        R_exp_z_basis = [z*x for x in R_exp_basis] # Basis of z*R_exp
        R_exp_z = V.subspace(R_exp_z_basis) # Space z*R_exp
        R_exp = R_exp.intersection(R_exp_z) # Update R_exp
        R_exp_basis = [Fqn(x.list()) for x in R_exp.basis()] # Update its basis
    if verbose:
        print(f"Dimension after contraction = {R_exp.dimension()}")
    return R_exp


    
# Expand contract   
def decoding_basic(R,V,Fqk,exp=4,intersect=1,verbose=False):
    R_basis = [Fqn(x.list()) for x in R.basis()]
    R_exp = V.subspace(R_basis) #Initialize the space we will expand.
    R_exp = expand_subspace(R_exp, V, Fqk, exp, verbose)
    R_exp = contract_subspace(R_exp, V, Fqk, intersect, verbose)
    return R_exp
    
# Expand contract fully expand    
def decoding_advance(R,V,Fqk,exp=3,intersect=1,verbose=False):
    R_basis = [Fqn(x.list()) for x in R.basis()]
    R_exp = V.subspace(R_basis) #Initialize the space we will expand.
    R_exp = expand_subspace(R_exp, V, Fqk, exp, verbose)
    R_exp = contract_subspace(R_exp, V, Fqk, intersect, verbose)
    R_exp = expand_subspace(R_exp, V, Fqk, Fqk.degree(), verbose)
    return R_exp



# Parameters
q = 2
# Dimensions of subspaces



# Encode a random word a*Fqk, then do some corruption
# Return (R,VA) the corrupted space and the indended one to verify
def corrupt_encode_random(V,Fqk, deletions, insertions,verbose=False):
    alpha = Fqk.gen()
    Vk = V.subspace([Fqn(alpha**i) for i in range(k)]) #Fqk as subspace of V = Fq^n
    Fqk_basis = [Fqn(x.list()) for x in Vk.basis()] # Basis of Fqk in V
    a = Fqn.random_element() # Random element ot encode
    while a == 0:
        a = Fqn.random_element()
    A_basis = [a*x for x in Fqk_basis] # Encoded subspace basis
    VA = V.subspace(A_basis) # Encoded susbspace
    B_basis = [Fqn.random_element() for i in range(insertions)] # Subspace to insert - basis 
    VB = V.subspace(B_basis) # Susbspace to insert
    if verbose:
        print(f"Insertion dimension = {VB.dimension()}")
    k - deletions
    VA_red = V.subspace([VA.random_element() for i in range(Fqk.degree() - deletions)]) # Take a subspace of dimension k-del from VA.
    if verbose:
        print(f"Erased dimension = {VA_red.dimension()}")
    R = VB + VA_red # Corrupted codeword.
    return (R,VA)
    

# RUn test for trials number of trial.
# Each round I generatea random example with a prescribed number of deletions and insertions
# I try to recover the same with 
# alg_1 = the basic algorithm 1 expansion , 1 contraction
# alg_2 = more advance where I do a large expansion and a large contraction
# alg_3 = the most advanced where I do a moderate expansion, followed by a moderate contraction and a full expansion
def test(V, Fqk, deletions, insertions, trials=100):
    counter_alg1= 0 # Algorithm exp = 2, intersect = 1
    counter_alg2= 0 # Algorithm exp = 5, intersect = 7 
    counter_alg3= 0 # Algorithm exp = 3, intersect = 2, exp = k
    for trial in range(trials):
        (R,VA) = corrupt_encode_random(V,Fqk, deletions, insertions, verbose=False) # Encode and corrupt a random element
        s = floor(V.degree()/(2*R.dimension()))
        if decoding_basic(R,V,Fqk,exp=2,intersect=1, verbose=False) == VA: # alg1 successful
            counter_alg1 += 1
        if decoding_basic(R,V,Fqk,exp=s+1,intersect=s+4, verbose=False) == VA: # alg2 successful
            counter_alg2 += 1
        if decoding_advance(R,V,Fqk,exp=s,intersect=2, verbose=False) == VA: # alg3 successful
            counter_alg3 += 1
    print(f"Success rate alg 1 = {float(100*(counter_alg1/trials))}%")    
    print(f"Success rate alg 2 = {float(100*(counter_alg2/trials))}%")  
    print(f"Success rate alg 3 = {float(100*(counter_alg3/trials))}%")
    return [counter_alg1,counter_alg2,counter_alg3]
    


# Real test
# Set parameters
k = 8
# n/k
r = 8
n = r*k

# Base field
Fq = GF(q, name='z')
# Define Fqn
#Fqn.<beta> = GF(q^n, name = 'beta')
Fqn = GF(q^n, name='y')
#alpha = Fqn.gen()
V = VectorSpace(Fq, n)
# The subfield Fqk
Fqk = Fqn.subfield(k, name = 'alpha')


(R,VA) = corrupt_encode_random(V,Fqk, 4, 4, verbose=False)
s = floor(V.degree()/(2*R.dimension()))
t_33 = test(V,Fqk, 3, 3, trials=1000)
t_36 = test(V,Fqk, 3, 6, trials=1000)
t_44 = test(V,Fqk, 4, 4, trials=1000)
t_55 = test(V,Fqk, 5, 5, trials=1000)
t_66 = test(V,Fqk, 6, 6, trials=1000)






